// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifi47b-_QrEhC2IzMHwoeZ4wIhuQ22xs',
    appId: '1:1070867048595:android:c4402300d9b1bd65bc4566',
    messagingSenderId: '1070867048595',
    projectId: 'newsapp-a4846',
    storageBucket: 'newsapp-a4846.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-enrv2qpieZ3Do-rfgmuA0VkDUB0JnTQ',
    appId: '1:1070867048595:ios:3ecbe5ad8ea920dbbc4566',
    messagingSenderId: '1070867048595',
    projectId: 'newsapp-a4846',
    storageBucket: 'newsapp-a4846.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-enrv2qpieZ3Do-rfgmuA0VkDUB0JnTQ',
    appId: '1:1070867048595:ios:3ecbe5ad8ea920dbbc4566',
    messagingSenderId: '1070867048595',
    projectId: 'newsapp-a4846',
    storageBucket: 'newsapp-a4846.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
